---
dist: bionic

language: python
python:
  - "3.6"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
# https://docs.travis-ci.com/user/common-build-problems/
branches:
  only:
    - master
    - dev

before_install:
  # Install apt packages
  - sudo apt update
  - sudo apt install -y python3-pip

install:
  # Install Ansible.
  - pip3 install ansible ansible-lint jmespath

script:
  # checks
  - which python
  - pip3 freeze
  # Check the role/playbook's syntax.
  - find . -name "*.yml" | xargs ansible-lint

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook wl-install.yml
