---
dist: bionic

branches:
  only:
    - master
    - dev

before_install:
  # Install apt packages
  - sudo apt update
  - sudo apt install -y python3-setuptools python3-pip

install:
  # Install Ansible.
  - pip3 install ansible ansible-lint jmespath
  # checks
  - which python3
  - python3 --version
  - pip3 freeze

script:
  # Check the role/playbook's syntax.
  - find . -name "*.yml" | xargs ansible-lint
  # Run the role/playbook with ansible-playbook.
  - ansible-playbook wl-install.yml
  - ansible-playbook wl-test.yml
